src_ref/ecsl/urls.py
from django.urls import path

from ecsl import Profile
from ecsl import becas
from ecsl import charlas as speechviews
from ecsl import contact
from ecsl import payment
from ecsl import views
from ecsl.webservice import get_calendar_json

urlpatterns = [
    path('', views.Index.as_view(), name="index"),
    path('api/agenda.json', get_calendar_json, name="api_json"),
    path('agenda', speechviews.Charlas.as_view(), name="list_charlas"),
    path('edit-agenda/<int:pk>', speechviews.EditCharlas.as_view(), name="edit_charlas"),
    path('miagenda', speechviews.MyAgenda.as_view(), name="mi_agenda"),

    path('charla/<int:pk>', speechviews.CharlaDetail.as_view(), name="detail_charla"),
    path('charla/registro/<int:pk>',
         speechviews.register_user_to_speech, name="registra_charla"),
    path('charla/desregistrar/<int:pk>',
         speechviews.desregistrar_charla, name="desregistrar_charla"),
    path('accounts/profile/', Profile.profile_view, name="profile"),
    path('register/profile/create',
         Profile.CreateProfile.as_view(), name='create_profile'),
    path('register/profile/update/<int:pk>', Profile.UpdateProfile.as_view(),
         name='edit_profile'),
    path('registro', payment.payment_view, name='payment'),
    path('registro/create', Profile.CreateRegister.as_view(), name='create_payment'),
    path('registro/update/<int:pk>', payment.PaymentUpdate.as_view(),
         name='edit_payment'),

    path('process-payment/<str:text>', payment.process_payment, name='process_payment'),
    path('payment-done/', payment.payment_done, name='payment_done'),
    path('payment-cancelled/', payment.payment_canceled, name='payment_cancelled'),
    path('sineventos/', views.noEvents, name='no-events'),
    path('becas/', becas.BecasCreate.as_view(), name="becas-create"),
    path('becas/detail/<int:pk>', becas.BecasDetail.as_view(), name="becas-detail"),
    path('contact/', contact.contactUs, name='contact-us'),
    path('contact/send/', contact.contact, name='contact'),
    path('participantes.js', views.get_participants, name="participantes"),
]

src_ref/ecsl_proj/urls.py
from django.contrib import admin

from django.conf.urls.static import static
from django.conf import settings

from ajax_select import urls as ajax_select_urls
from django.urls import include, path, re_path



urlpatterns = [
    re_path(r'^ajax_select/', include(ajax_select_urls)),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^ajax_select/', include(ajax_select_urls)),
    re_path(r'^accounts/', include('django_registration.backends.activation.urls')),
    re_path(r'^accounts/', include('django.contrib.auth.urls')),
    re_path(r'^paypal/', include('paypal.standard.ipn.urls')),
    re_path(r'', include('ecsl.urls')),
    re_path(r'^proposal/', include('proposal.urls')),
    path('captcha/', include('captcha.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  #+ views.becas


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

src_ref/proposal/urls.py
# encoding: utf-8

'''
Free as freedom will be 27/10/2016

@author: luisza
'''

from __future__ import unicode_literals

from rest_framework.routers import DefaultRouter

from proposal import views, types, topics, special_activities, rooms
from django.urls import path, include

from proposal.views import EventScheduleViewSet

router = DefaultRouter()
router.register(r'schedule/events', EventScheduleViewSet, basename='events')

app_name = 'proposal'
urlpatterns = [
    path('', views.SpeechListView.as_view(), name='speech-list'),
    path('create/', views.createUpdateview, name='create'),
    path('<int:speech_id>/update/', views.createUpdateview, name='update'),
    path('<int:speech_id>/delete/', views.deleteView, name='delete'),
    path('createTopic/', topics.CreateTopic.as_view(), name='create-topic'),
    path('createType/', types.CreateType.as_view(), name='create-type'),
    path('createRoom/', rooms.CreateRoom.as_view(), name='create-room'),
    path('filterSpeeches/', views.get_all_speeches, name='filter-speeches'),
    path('createSpecial/', special_activities.CreateSpecialActivity.as_view(), name='create-special'),
    path('schedule/events/delete-events/', views.removeSpeechScheduleFromCalendarView, name='delete-events'),
]

urlpatterns += router.urls

src_ref/proposal/models.py
import uuid

from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import ugettext_lazy as _

from ecsl.managers import CurrentEventManager
from ecsl.models import EventECSL


class Topic(models.Model):
    name = models.CharField(max_length=150, verbose_name=_("Name"))
    color = models.CharField(max_length=10, default="#fff")
    event = models.ForeignKey(EventECSL, on_delete=models.CASCADE, null=True, blank=False, verbose_name=_("Event"))
    objects = CurrentEventManager()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Temática"
        verbose_name_plural = "Temáticas"


class SpeechType(models.Model):
    name = models.CharField(max_length=150, verbose_name=_("Name"))
    time = models.IntegerField(default=10, verbose_name=_("Duration (in minutes)"))
    event = models.ForeignKey(EventECSL, null=True, default=None, on_delete=models.CASCADE, verbose_name=_("Event"))
    is_special = models.BooleanField(default=False, verbose_name=_('Is Special Activity'))
    objects = CurrentEventManager()

    def __str__(self):
        return _("%s (%d minutes)") % (self.name, self.time)

    class Meta:
        verbose_name = "Tipo de actividad"
        verbose_name_plural = "Tipos de actividad"


class Speech(models.Model):
    class SKILL_LEVEL:
        EVERYONE = 1
        NOVICE = 2
        INTERMEDIATE = 3
        ADVANCED = 4

        choices = [
            (EVERYONE, _('everyone')),
            (NOVICE, _('novice')),
            (INTERMEDIATE, _('intermediate')),
            (ADVANCED, _('advanced')),
        ]

    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name=_('Usuario'))
    speaker_information = models.TextField(
        verbose_name=_("Speaker_information"))
    title = models.TextField(verbose_name=_("Speech Title"))
    description = models.TextField(verbose_name=_("Description"))
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE,
                              verbose_name=_("Topic"))
    audience = models.TextField(verbose_name=_("Audience"))
    skill_level = models.PositiveIntegerField(
        choices=SKILL_LEVEL.choices, default=SKILL_LEVEL.EVERYONE,
        verbose_name=_("Skill level required"))
    notes = models.TextField(blank=True,
                             verbose_name=_("Notes for audience"))
    speech_type = models.ForeignKey(SpeechType, on_delete=models.CASCADE, verbose_name=_("Speech Types"))
    presentacion = models.FileField(upload_to='presentaciones/',
                                    verbose_name=_("Presentation"),
                                    null=True, blank=True)
    event = models.ForeignKey(EventECSL, null=True, blank=False, on_delete=models.CASCADE, verbose_name=_("Event"))
    is_scheduled = models.BooleanField(default=False, verbose_name=_('is Scheduled'))
    speech_time_asked = models.IntegerField(default=0, verbose_name=_("Time Asked"))
    objects = CurrentEventManager()

    @property
    def speaker_name(self):
        return self.user.get_full_name()

    @property
    def speaker_registered(self):
        dev = False
        try:
            dev = self.user.payment.confirmado
        except:
            pass
        return dev

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('pk',)
        # permissions = (
        #     ("view_speech", "Can see available Speech"),
        # )

        verbose_name = "Actividad"
        verbose_name_plural = "Actividades"


class Room(models.Model):
    name = models.CharField(max_length=100, verbose_name=_('Nombre'))
    spaces = models.SmallIntegerField(default=30, verbose_name=_('Spaces'))
    map = models.ImageField(upload_to="mapa", null=True, blank=True, verbose_name=_('Map'))
    event = models.ForeignKey(EventECSL, on_delete=models.CASCADE, verbose_name=_("Event"), null=True, default=None)
    objects = CurrentEventManager()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Sala"
        verbose_name_plural = "Salas"


class Register_Speech(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    speech = models.ForeignKey('SpeechSchedule', on_delete=models.CASCADE)

    def __str__(self):
        return "%s %s" % (self.user.get_full_name(), self.speech.speech.title)

    class Meta:
        verbose_name = "Registro en actividad"
        verbose_name_plural = "Registros en actividades"


class SpeechSchedule(models.Model):
    html_id = models.UUIDField(default=uuid.uuid4, unique=True)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    speech = models.ForeignKey(Speech, on_delete=models.CASCADE, null=True, blank=True)
    special = models.ForeignKey('SpecialActivity', on_delete=models.CASCADE, null=True, blank=True)
    room = models.ForeignKey('Room', on_delete=models.CASCADE, null=True, default=None)

    def __str__(self):
        return "(%s %s) %s" % (self.start_time.strftime("%Y-%m-%d %H:%M"),
                                     self.end_time.strftime("%Y-%m-%d %H:%M"),
                                     self.room.name)

    @property
    def title(self):
        return self.room.name + " "+str(self.start_time)+" "+str(self.end_time)

    def registros(self):
        regs = Register_Speech.objects.filter(speech=self).count()
        total = self.room.spaces - regs

        dev = "Lleno"
        if total > 0:
            dev = "Hay %d espacios" % (total,)

        return dev

    class Meta:
        verbose_name = "Horario de actividad"
        verbose_name_plural = "Horarios de actividades"


class SpecialActivity(models.Model):
    name = models.CharField(max_length=100, verbose_name=_('Name'))
    type = models.ForeignKey(SpeechType, null=True, on_delete=models.CASCADE, verbose_name=_("Type"))
    message = models.TextField(null=True, blank=True, verbose_name=_("Message"))
    room = models.ForeignKey('Room', null=True, default=None, blank=True, on_delete=models.CASCADE, verbose_name=_("Room"))
    event = models.ForeignKey(EventECSL, default="", on_delete=models.CASCADE, verbose_name=_("Event"))
    is_scheduled = models.BooleanField(default=False, verbose_name=_('is Scheduled'))
    objects = CurrentEventManager()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Actividad Especial"
        verbose_name_plural = "Actividades Especiales"


class BlockSchedule(models.Model):
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    is_speech = models.BooleanField()
    text = models.TextField(null=True, blank=True)
    color = models.CharField(max_length=10)
    room = models.ForeignKey('Room', null=True, default=None, on_delete=models.CASCADE, verbose_name=_("Room"))

    def __str__(self):
        return "%s %s" % (self.start_time.strftime("%Y-%m-%d %H:%M"),
                          self.end_time.strftime("%Y-%m-%d %H:%M"),)

    def get_speech(self, user=None):
        query = SpeechSchedule.objects.filter(
            start_time=self.start_time,
        )
        if user:
            query = query.filter(register_speech__user=user)

        return query.order_by('start_time')

    class Meta:
        verbose_name = "Bloque de horario"
        verbose_name_plural = "Bloques de horarios"

src_ref/proposal/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from .models import Speech, Topic, SpeechType, SpecialActivity, Room


class SpeechForm(forms.ModelForm):
    speech_type = forms.ModelChoiceField(queryset=SpeechType.objects.filter(is_special=False), label=_("Type"))

    class Meta:
        model = Speech
        exclude = ('user', 'event', 'is_scheduled', 'speech_time_asked')


class TopicForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['color'].widget.input_type='color'

    class Meta:
        model = Topic
        fields = '__all__'
        widgets = {
            'event': forms.HiddenInput,
            'color': forms.TextInput(attrs={'class': "form-control form-control-color"})
        }


class TypeForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['time'].widget.input_type = 'range'

    class Meta:
        model = SpeechType
        fields = '__all__'
        widgets = {
            'event': forms.HiddenInput,
            'time': forms.TextInput(attrs={'step': "10", 'min': "10", 'max': "480"})
        }


class SpecialActivityForm(forms.ModelForm):
    type = forms.ModelChoiceField(queryset=SpeechType.objects.filter(is_special=True), label=_("Type"))

    class Meta:
        model = SpecialActivity
        exclude = ('is_scheduled', 'room')
        widgets = {
            'event': forms.HiddenInput,
            'message': forms.Textarea(attrs={'rows': 4}),
        }


class RoomsCreateForm(forms.ModelForm):
    class Meta:
        model = Room
        exclude = ('event',)

src_ref/proposal/templates/proposal/agenda.html
{% extends 'base.html' %}
{% load i18n %}
{% load bootstrap %}
{% load registro_charla %}
{% load static %}
{% block css %}
    <link href="{% static 'css/proposal.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}
    <div id="calendar-container">
        <ul class="nav nav-tabs" id="roomTabs" role="tablist" style="padding: 10px;">
            {% for room in rooms_list %}
                <li class="nav-item">
                    <a class="nav-item nav-link room-tab" id="calendar-{{forloop.counter}}-tab" data-toggle="tab" data-room-id="{{room.id}}" data-num="{{forloop.counter}}" href="#calendar-{{forloop.counter}}" role="tab" aria-controls="calendar-{{forloop.counter}}" aria-selected="false">{{ room }}</a>
                </li>
            {% endfor %}
        </ul>
        <div class="tab-content" id="calendarContent">
            {% for room in rooms_list %}
                <div class="full-calendar tab-pane fade" id="calendar-{{forloop.counter}}" role="tabpanel" aria-labelledby="calendar-{{forloop.counter}}-tab" data-start_date="{{start_date}}" data-end_date="{{ end_date }}"></div>
            {% endfor %}
        </div>
    </div>
    <div class="modal fade" role="dialog" id="room_modal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h2 class="modal-title text-center">{% trans 'Create Room' %}</h2>
                </div>
                <div class="modal-body">
                    <form name="roomForm" action="proposal/createRoom/" method="post">
                        {% csrf_token %}
                        {{ room_form|bootstrap }}
                        <input name="form_id" value="roomForm" hidden>
                        <br>
                        <div class="form-group text-center">
                            <input type="submit" name="action" class="btn btn-primary" value="{% trans 'Save Room' %}">
                            <button type="button" class="btn btn-secondary"
                                    data-dismiss="modal">{% trans 'Close' %}</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script>
        var save_url = "{% url 'proposal:events-list' %}";
        var delete_url = "{% url 'proposal:delete-events' %}";
        var scheduled_events = [];
        {% for event in scheduled_speeches %}
            {% if event.speech %}
                scheduled_events.push({
                    id: "{{event.pk}}",
                    html_id: "{{event.html_id}}",
                    title: "{{event.speech.title}}",
                    color: "{{event.speech.topic.color}}",
                    room: "{{event.room.pk}}",
                    start_time: "{{event.start_time|date:"c"}}",
                    end_time: "{{event.end_time|date:"c"}}",
                    speech_id: "{{event.speech.pk}}",
                    topic_id: "{{event.speech.topic.pk}}",
                    speech_type_id: "{{event.speech.speech_type.pk}}",
                    speech_type_time: "{{event.speech.speech_type.time}}",
                    speech_type_name: "{{event.speech.speech_type.name}}",
                });
            {% else %}
                scheduled_events.push({
                    id: "{{event.pk}}",
                    html_id: "{{event.html_id}}",
                    title: "{{event.special.name}}",
                    room: "{{event.room.pk}}",
                    start_time: "{{event.start_time|date:"c"}}",
                    end_time: "{{event.end_time|date:"c"}}",
                    special_id: "{{event.special.pk}}",
                    speech_type_id: "{{event.special.speech_type.pk}}",
                    speech_type_time: "{{event.special.speech_type.time}}",
                    speech_type_name: "{{event.special.speech_type.name}}",
                });
            {% endif %}
        {% endfor %}
        const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
        var create_topic_url = "{% url 'proposal:create-topic' %}";
        var create_type_url = "{% url 'proposal:create-type' %}";
        var save_name = "{% trans 'Save' %}";
        var whole_event_name = "{% trans 'whole event' %}";
        var day_name = "{% trans 'day' %}";
    </script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://cdn.jsdelivr.net/combine/npm/fullcalendar@5.10.1,npm/fullcalendar@5.10.1/locales-all.min.js,npm/fullcalendar@5.10.1/locales-all.min.js,npm/fullcalendar@5.10.1/main.min.js"></script>
    <script src='https://cdn.jsdelivr.net/npm/rrule@2.6.4/dist/es5/rrule.min.js'></script>
    <script src='https://cdn.jsdelivr.net/npm/@fullcalendar/rrule@5.5.0/main.global.min.js'></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/combine/npm/fullcalendar@5.10.1/main.min.css,npm/fullcalendar@5.10.1/main.min.css">
    <script src="{% static 'js/agenda.js' %}"></script>
{% endblock %}

src_ref/proposal/templates/proposal/edit_agenda.html
{% extends 'base.html' %}
{% load i18n %}
{% load bootstrap %}
{% load registro_charla %}
{% load static %}

{% block content %}
<div class="row">
    <div class="col-md-3">
    </div>
    <div class="col-md-9">
    </div>
</div>


{% endblock %}

src_ref/proposal/templates/proposal/mi_agenda.html
{% extends 'base.html' %}
{% load i18n %}
{% load registro_charla %}

{% block content %}
<style>
.theader{
	text-decoration: blond;
	background-color: #98978b;
	padding: 10px 2px;
	text-align: center;
	color: #fff;
	margin-bottom: 5px;
}

.speech_row {
	
	padding: 10px 5px;
	text-align: left;
}

.text_row  {
	padding: 10px 0px;
	color: #fff;
	font-weight: bold;
}
</style>
<div class="pull-right">
<a class="btn btn-danger" href="{% url 'list_charlas' %}?dia=1"> Ver todos los eventos </a>
</div>

<br><br>
<h2> Temáticas </h2>


<div class="row">
 <div class="col-md-1"></div>
{% for tipo in tipos %}
 <div class="col-md-2" style="color: {{tipo.color}}"> {{tipo.name }} </div>
{% endfor %}
</div>


<hr>

<ul class="nav nav-tabs">
  {% for d in dayList %}
        <li role="presentation" class="{% if dia ==  forloop.counter  %} active {% endif %}">
        <a href="{% url 'mi_agenda' %}?dia={{ forloop.counter }}">{{ d }}</a></li>
  {% endfor %}


</ul>
<br ><br>


<div class="row theader">
  <div class="col-md-2">Horario</div>
  <div class="col-md-5">Título</div>
   <div class="col-md-2">Expositor/a responsable</div>
  <div class="col-md-1">Salón</div>
  <div class="col-md-2">Registro</div>
</div>

	{% for obj in object_list %}
		
		<div id="block_{{obj.pk}}" class="row {% if obj.is_speech %}speech_row{% else %} text_row {%endif%}" style="background-color:{{obj.color}}">
		{% if obj.is_speech %}
		  {% get_speech obj as sobj %}
		  {% for speech in sobj %}
		  <div class="row">
		  <div class="col-md-2">{{ speech.start_time | date:"P" }} a {{ speech.end_time | date:"P" }}
		  		  	<p style="color:{{ speech.speech.topic.color}}">
				{{ speech.speech.speech_type.name }}
				</p>
		  </div>
		  <div class="col-md-5">

			<a href="{% url 'detail_charla' speech.speech.pk %}" target="_blank"> {{ speech.speech.title }} </a>
		  </div>
		  <div class="col-md-2">{{ speech.speech.user.get_full_name }}</div>
		  <div class="col-md-1">{{ speech.room.name }}</div>
		  <div class="col-md-2">  {% get_registro speech as nreg%}  <a href="{{nreg.url}}"> {{nreg.message}} </a> </div>
		  </div>
			{% endfor %}
			
		{% else %}
		<div class="col-md-2 text-center"> {{ obj.start_time | date:"P" }} a {{ obj.end_time | date:"P" }} </div>
		<div class="col-md-10 text-center"> {{obj.text}}</div>
		
		{% endif %}
		</div>	
	{% endfor %}

<br><br>
{% endblock %}

src_ref/proposal/templates/proposal/speech_detail.html
{% extends 'base.html' %}
{% load i18n %}
{% load registro_charla %}
{% block content %}

<h2 style="color: {{object.topic.color}}"> {{ object.title }}<br>
<small> {{ object.topic.name }} </small>
</h2>

<div class="panel panel-success">
  <div class="panel-heading">
  <div class="row">
  <div class="col-md-6">{{object.speech_type}}</div>
  <div class="col-md-4">
  
  {{ schedule.start_time | date:"SHORT_DATE_FORMAT"  }} -- {{ schedule.start_time | date:"P" }} a {{ schedule.end_time | date:"P" }}
  </div>
  <div class="col-md-2">
  {% get_registro schedule as nreg%}  <a class="btn btn-info" href="{{nreg.url}}"> {{nreg.message}} </a>

  </div>
</div>
  
    
  </div>

  <div class="panel-body">
  
    {{ object.description }}
    {% if object.audience and object.audience != " " %}
    	<h2 > Audiencia </h2>
    	{{ object.audience }}
    {% endif %}
  </div>
  <div class="panel-footer">
  <b>Nivel</b>: {{object.get_skill_level_display}} <br>
  {% if object.presentation %}
  <a href="{{object.presentation.url" class="btn btn-warning"> Descargar presentación </a> 
  {% endif %}
  </div>
</div>

<div class="panel panel-danger">
  <div class="panel-heading">
    <h3 class="panel-title">Información (los/las) expositor(es/as)</h3>
  </div>
  <div class="panel-body">
    {{object.speaker_information }}
  </div>
</div>

{% if object.notes and object.notes != " " %}
<div class="alert alert-info">
	{{object.notes}}
</div>
{% endif %}

{% endblock %}

src_ref/proposal/templates/proposal/speech_form.html
{% extends 'base.html' %}

{% load bootstrap  i18n %}

{% block content %}
<div class="row">
	<div class="col-md-6 col-md-offset-4">
<h1 align="center">Propuesta para charlas en el encuentro</h1>
    <form method="post">{% csrf_token %}
    {{ speech_form|bootstrap  }}
    <input class="btn btn-info" type="submit" value="{% trans 'Save' %}">
</form>
</div></div>
<br> <br>
{% endblock %}

src_ref/proposal/templates/proposal/speech_list.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
    {% if period %}
        <a class="btn btn-info"
           href="{% url 'proposal:create' %}">

            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> {% trans 'Add' %} </a>

    {% endif %}
    <br> <br>
    <ul class="list-group">
        {% for object in object_list %}
            <li class="row list-group-item">
                <div class="col-md-9"> {{ object }}</div>
                <form action="{% url 'proposal:delete' object.pk %}" method="POST">
                    {% csrf_token %}
                    <div class="col-md-3">
                        <a class="btn btn-info"
                           href="{% url 'proposal:update' object.pk %}">
                            <span class="glyphicon glyphicon-edit" aria-hidden="true"></span> {% trans 'Edit' %}</a>

                        <button class="btn btn-danger">
                            <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> {% trans 'Delete' %}
                        </button>
                    </div>
                </form>
            </li>
        {% endfor %}
    </ul>

    {% if is_paginated %}
        <nav aria-label="...">
            <ul class="pager">
                {% if page_obj.has_previous %}
                    <li>
                        <a href="?page={{ page_obj.previous_page_number }}">{% trans 'Previous' %}</a>
                    </li>
                {% endif %}

                <li>
                    {% trans 'Page' %} {{ page_obj.number }} -- {{ page_obj.paginator.num_pages }}.
                </li>

                {% if page_obj.has_next %}
                    <li>
                        <a href="?page={{ page_obj.next_page_number }}">{% trans 'Next' %}</a>
                    </li>
                {% endif %}
            </ul>
        </nav>

    {% endif %}

{% endblock %}