src_ref/ecsl/urls.py
from django.urls import path

from ecsl import Profile
from ecsl import becas
from ecsl import charlas as speechviews
from ecsl import contact
from ecsl import payment
from ecsl import views
from ecsl.webservice import get_calendar_json

urlpatterns = [
    path('', views.Index.as_view(), name="index"),
    path('api/agenda.json', get_calendar_json, name="api_json"),
    path('agenda', speechviews.Charlas.as_view(), name="list_charlas"),
    path('edit-agenda/<int:pk>', speechviews.EditCharlas.as_view(), name="edit_charlas"),
    path('miagenda', speechviews.MyAgenda.as_view(), name="mi_agenda"),

    path('charla/<int:pk>', speechviews.CharlaDetail.as_view(), name="detail_charla"),
    path('charla/registro/<int:pk>',
         speechviews.register_user_to_speech, name="registra_charla"),
    path('charla/desregistrar/<int:pk>',
         speechviews.desregistrar_charla, name="desregistrar_charla"),
    path('accounts/profile/', Profile.profile_view, name="profile"),
    path('register/profile/create',
         Profile.CreateProfile.as_view(), name='create_profile'),
    path('register/profile/update/<int:pk>', Profile.UpdateProfile.as_view(),
         name='edit_profile'),
    path('registro', payment.payment_view, name='payment'),
    path('registro/create', Profile.CreateRegister.as_view(), name='create_payment'),
    path('registro/update/<int:pk>', payment.PaymentUpdate.as_view(),
         name='edit_payment'),

    path('process-payment/<str:text>', payment.process_payment, name='process_payment'),
    path('payment-done/', payment.payment_done, name='payment_done'),
    path('payment-cancelled/', payment.payment_canceled, name='payment_cancelled'),
    path('sineventos/', views.noEvents, name='no-events'),
    path('becas/', becas.BecasCreate.as_view(), name="becas-create"),
    path('becas/detail/<int:pk>', becas.BecasDetail.as_view(), name="becas-detail"),
    path('contact/', contact.contactUs, name='contact-us'),
    path('contact/send/', contact.contact, name='contact'),
    path('participantes.js', views.get_participants, name="participantes"),
]

src_ref/ecsl_proj/urls.py
from django.contrib import admin

from django.conf.urls.static import static
from django.conf import settings

from ajax_select import urls as ajax_select_urls
from django.urls import include, path, re_path



urlpatterns = [
    re_path(r'^ajax_select/', include(ajax_select_urls)),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^ajax_select/', include(ajax_select_urls)),
    re_path(r'^accounts/', include('django_registration.backends.activation.urls')),
    re_path(r'^accounts/', include('django.contrib.auth.urls')),
    re_path(r'^paypal/', include('paypal.standard.ipn.urls')),
    re_path(r'', include('ecsl.urls')),
    re_path(r'^proposal/', include('proposal.urls')),
    path('captcha/', include('captcha.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  #+ views.becas


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

src_ref/proposal/urls.py
# encoding: utf-8

'''
Free as freedom will be 27/10/2016

@author: luisza
'''

from __future__ import unicode_literals

from rest_framework.routers import DefaultRouter

from proposal import views, types, topics, special_activities, rooms
from django.urls import path, include

from proposal.views import EventScheduleViewSet

router = DefaultRouter()
router.register(r'schedule/events', EventScheduleViewSet, basename='events')

app_name = 'proposal'
urlpatterns = [
    path('', views.SpeechListView.as_view(), name='speech-list'),
    path('create/', views.createUpdateview, name='create'),
    path('<int:speech_id>/update/', views.createUpdateview, name='update'),
    path('<int:speech_id>/delete/', views.deleteView, name='delete'),
    path('createTopic/', topics.CreateTopic.as_view(), name='create-topic'),
    path('createType/', types.CreateType.as_view(), name='create-type'),
    path('createRoom/', rooms.CreateRoom.as_view(), name='create-room'),
    path('filterSpeeches/', views.get_all_speeches, name='filter-speeches'),
    path('createSpecial/', special_activities.CreateSpecialActivity.as_view(), name='create-special'),
    path('schedule/events/delete-events/', views.removeSpeechScheduleFromCalendarView, name='delete-events'),
]

urlpatterns += router.urls

src_ref/ecsl/forms.py
'''
Created on 2 jun. 2017

@author: luis
'''
from django import forms
from django.utils.translation import ugettext_lazy as _

from ecsl.models import Inscription, Payment, PaymentOption
from proposal.models import SpeechSchedule


class ProfileForm(forms.ModelForm):
    first_name = forms.CharField(label=_("First name"))
    last_name = forms.CharField(label=_("Last name"))

    field_order = [
        'first_name', 'last_name',
        'identification',
        'direccion_en_su_pais',
        'nationality', 'other_nationality',
        'gender', 'camiseta',
        'born_date', 'institution',
        'encuentros',
        'alimentary_restriction', 'health_consideration',
        'gustos_manias', 'observacion_gustos_manias',
        'comentario_general',
        'hora_de_llegada', 'hora_de_salida', 'medio_de_transporte',
        'lugar_de_arribo', 'observaciones_del_viaje', 'aparecer_en_participantes'
    ]

    def __init__(self, *args, **kwargs):
        self.user = None
        if 'instance' in kwargs and kwargs['instance']:
            self.user = kwargs['instance'].user

        if 'request' in kwargs:
            request = kwargs.pop('request')
            self.user = request.user
        if self.user:
            kwargs['initial']['first_name'] = self.user.first_name
            kwargs['initial']['last_name'] = self.user.last_name

        super(ProfileForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        dev = super(ProfileForm, self).save(commit=commit)
        user = None
        if self.instance:
            user = self.instance.user
        elif self.user:
            user = self.user
        if user:
            user.first_name = self.cleaned_data['first_name']
            user.last_name = self.cleaned_data['last_name']
            user.save()
        return dev

    class Meta:
        model = Inscription
        fields = '__all__'
        exclude = ['user', 'status', 'event']


class PaymentForm(forms.ModelForm):
    option = forms.ModelChoiceField(widget=forms.RadioSelect,
                                    queryset=PaymentOption.objects.all().exclude(name="Beca").exclude(name="Paypal"),
                                    label="Opción de pago",
                                    empty_label=None)

    class Meta:
        model = Payment
        fields = '__all__'
        exclude = ['user', 'confirmado', 'event']


class ContactForm(forms.Form):
    Name = forms.CharField(
        label=False,
        min_length=2,
        max_length=50,
        widget=forms.TextInput(
            attrs={
                'placeholder': _('Name'),
                'class': 'form-control',
            }
        )
    )

    Email = forms.CharField(
        label=False,
        min_length=6,
        max_length=50,
        widget=forms.EmailInput(
            attrs={
                'placeholder': _('Email'),
                'class': 'form-control',
            }
        )
    )

    Subject = forms.CharField(
        label=False,
        min_length=2,
        max_length=150,
        widget=forms.TextInput(
            attrs={
                'placeholder': _('Subject'),
                'class': 'form-control',
            }
        )
    )

    Message = forms.CharField(
        label=False,
        widget=forms.Textarea(
            attrs={
                'placeholder': _('Message'),
                'class': 'form-control',
            }
        )
    )


class scheduleForm(forms.ModelForm):
    is_speech = forms.BooleanField(required=False)
    text = forms.CharField(max_length=250)
    color = forms.CharField(max_length=10)

    class Meta:
        model = SpeechSchedule
        fields = '__all__'

src_ref/ecsl/views.py
import hashlib
import random
import urllib

from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.base import TemplateView
from django.urls.base import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from ecsl.models import Inscription, Payment, Becas, EventECSL, Package, PaymentOption
from django.utils.decorators import method_decorator
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.detail import DetailView
from django.contrib import messages
from ecsl.forms import ProfileForm, PaymentForm, ContactForm
from django.utils.translation import ugettext_lazy as _
from django.conf import settings
from captcha.fields import CaptchaField
from django.core.mail import EmailMessage, send_mail
from django.core.mail import send_mail
from django.db.models import Count, Q


def noEvents(request):
    current_event = EventECSL.objects.filter(current=True).first()
    if current_event:
        return redirect('index')
    return render(request, 'no_events.html')


class Index(TemplateView):
    template_name = 'index.html'

    def dispatch(self, request, *args, **kwargs):
        current_event = EventECSL.objects.filter(current=True).first()
        if not current_event:
            return redirect('no-events')
        return super(Index, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        proposal = None
        current_event = EventECSL.objects.filter(current=True).first()

        context = TemplateView.get_context_data(self, **kwargs)
        if self.request.user.is_authenticated:
            try:
                proposal = self.request.user.speech_set.count()
                if proposal > 0:
                    proposal = True
                else:
                    proposal = False
            except Exception as e:
                pass
            beca = Becas.objects.filter(user=self.request.user, event=current_event).first()
            if beca:
                context['becas_period'] = True
                context['beca'] = reverse_lazy('becas-detail')
            else:
                context['becas_period'] = current_event.is_beca_active
                context['beca'] = reverse_lazy('becas-create')
            if proposal:
                context['speech_url'] = proposal

        context['numparticipantes'] = Payment.objects.filter(event=current_event).count()
        context['genero'] = {
            'masculino': Payment.objects.filter(user__inscription__gender='Masculino', event=current_event).count(),
            'femenino': Payment.objects.filter(user__inscription__gender='Femenino', event=current_event).count(),
            'otro': Payment.objects.filter(user__inscription__gender='Otro', event=current_event).count(),
        }

        parms = {
            'panama': Count('user__inscription__nationality', filter=Q(user__inscription__nationality='Panamá')),
            'costarica': Count('user__inscription__nationality', filter=Q(user__inscription__nationality='Costa Rica')),
            'nicaragua': Count('user__inscription__nationality', filter=Q(user__inscription__nationality='Nicaragua')),
            'elsalvador': Count('user__inscription__nationality', filter=Q(user__inscription__nationality='El Salvador')),
            'guatemala': Count('user__inscription__nationality', filter=Q(user__inscription__nationality='Guatemala')),
            'honduras': Count('user__inscription__nationality', filter=Q(user__inscription__nationality='Honduras')),
            'belize': Count('user__inscription__nationality', filter=Q(user__inscription__nationality='Belize')),
            'otro': Count('user__inscription__nationality', filter=Q(user__inscription__nationality='Otro')),
        }

        context['pais'] = Payment.objects.filter(event=current_event).aggregate(**parms)

        if current_event.checking_period:
            context['period'] = current_event.checking_period
        elif proposal:
            context['period'] = True
        context['event_name'] = str(current_event)
        context['event_logo'] = current_event.logo
        date = _("from %(start)s to %(end)s") % {'start': current_event.start_date.strftime("%B %-d"),
                                                 'end': current_event.end_date.strftime("%B %-d, %Y")}
        context['event_dates'] = date
        context['event_location'] = current_event.location
        context['event_description'] = current_event.description
        context['event_id'] = current_event.pk

        return context


def get_participants(request):
    dev = []
    default = "https://ecsl2017.softwarelibre.ca/wp-content/uploads/2017/01/cropped-photo_2017-01-30_20-55-06.jpg".encode(
        'utf-8')
    size = 50
    for payment in Payment.objects.all().order_by('?'):
        email = payment.user.email.lower().encode('utf-8')

        insc = Inscription.objects.filter(user=payment.user).first()
        if insc and insc.aparecer_en_participantes:
            name = payment.user.get_full_name()

            url = "https://www.gravatar.com/avatar/%s?%s" % (hashlib.md5(
                email).hexdigest(), urllib.parse.urlencode({'d': default, 's': str(size)}))

            dev.append({'url': url, 'name': name})

    return JsonResponse(dev, safe=False)

src_ref/ecsl/templates/base.html
{% load static %}
{% load i18n %}
{% load event_tag %}
<!DOCTYPE html>
<html lang="en">
<head>
    {# METADATA  #}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {# TITLE #}
    <title>ECSL | {% block title %}Index{% endblock %}</title>

    {# CSS #}

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <script src="https://kit.fontawesome.com/b925bcad50.js" crossorigin="anonymous"></script>

    {% block css %}{% endblock %}
</head>
<body>

 {# NAV #}

{% include 'partial/top_navbar.html' %}

<div class="{% block container %}container{% endblock %}">

    {# CONTENT #}

    {% if messages %}


        <div class="alert alert-warning alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                    aria-hidden="true">&times;</span></button>

            {% for message in messages %}
                {{ message }}<br>
            {% endfor %}

        </div>
    {% endif %}


    {% block content %}
    {% endblock %}
</div>
{# FOOTER #}
{% include 'partial/footer.html' %}
<div class="jsmessage"></div>
{# JS #}
<script src="{% static 'js/jquery-1.10.2.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
{% block js %}{% endblock %}
</body>
</html>

src_ref/ecsl/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-8"><h1>{% trans 'Central American Free Software Meeting ' %}</h1></div>

            <div class="col-md-2 ">

            </div>
        </div>

    </div>
    <br><br>
    <div class="row">
        <div class="col-md-12">
            <div class="well">
                <div class="row">
                    <div class="col-md-4 text-center">
                        <img class="img-responsive" src=" {{ event_logo.url }}" alt="Logo">
                    </div>
                    <div class="col-md-6">
                        <h3>{{ event_name }}<small> <b></b> {{ event_dates }} </small></h3>
                        <p>{{ event_location }}</p>
                        <p>
                        </p>
                        <p>{{ event_description }}</p>

                        <p></p>
                    </div>
                    <div class="col-md-2">
                        <div class="btn-group-vertical">
                            {% if request.user.is_authenticated %}
                                <a class="btn btn-default" href="{% url 'profile' %}">
                                    <i class="fas fa-id-card"></i> {% trans 'My profile' %}
                                </a>
                                <a class="btn btn-warning" href="{% url 'payment' %}">
                                    <i class="fas fa-user-plus"></i> {% trans 'Sign Up' %}
                                </a>
                                {% if becas_period %}
                                    <a class="btn btn-success" href="{% url 'becas-create' %}">
                                        <i class="fas fa-money-check-alt"></i> {% trans 'Scholarship' %}
                                    </a>
                                {% endif %}
                                {% if period %}
                                    <a class="btn btn-default"
                                       href="{% url 'proposal:speech-list' %}">
                                        <i class="fas fa-chalkboard-teacher"></i> {% trans 'My speeches' %}
                                    </a>
                                {% endif %}
                                <a class="btn btn-danger" href="{% url 'mi_agenda' %}">
                                    <i class="fas fa-calendar-week"></i> {% trans 'My agenda' %}
                                </a>
                            {% else %}
                                <a class="btn btn-info" href="{% url 'login' %}">
                                    <i class="fas fa-sign-in-alt"></i> {% trans 'Login' %}
                                </a>
                                <a class="btn btn-default"
                                   href="{% url 'django_registration_register' %}">
                                    <i class="fas fa-user-plus"></i> {% trans 'Sign Up' %}
                                </a>
                            {% endif %}
                            <a class="btn btn-info" href="{% url 'list_charlas' %}">
                               <i class="fas fa-calendar-alt"></i> {% trans 'Agenda' %}
                            </a>
                            {% if request.user.is_authenticated and request.user.is_staff %}
                            <a class="btn btn-primary" href="{% url 'edit_charlas' pk=event_id %}">
                               <i class="fas fa-pen-square"></i> {% trans 'Build agenda' %}
                            </a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="row">
        <div class="page-header">
            <h1 class="text-center text-warning">Ya somos {{ numparticipantes }} participantes </h1></div>
        <div id="participantes" class="list-group col-md-8 ">

        </div>
        <div class="col-md-4 ">

            <h3 class="text-center"> Distribución por género </h3>
            <canvas id="genero"></canvas>
            <h3 class="text-center"> Distribución por país </h3>
            <canvas id="pais"></canvas>

        </div>
    </div>

    <div class="row">
        <div class="page-header col-md-8 col-md-offset-2">
            <h2 class="text-center text-warning"> Sea parte de nuestra comunidad; <br>aprenda, comparta, colabore y
                disfrute con nosotros. </h2>
        </div>
    </div>

    </div>

{% endblock %}

{% block js %}

    <script>
        $.get("{% url "participantes" %}", function (data) {

            var li = '<div class="col-md-1"> <img width="50px" heigth="50px"  src="url" alt="altnombre" class="img-circle"></div>';
            li += '<div class="col-md-3">nombre</div>';

            var item = "";
            var p = 0;
            var t = "bg-info";
            for (var x = 0; x < data.length; x++) {
                if (x % 3 == 0) {
                    if (x != 0) item += '</div>';
                    if (p % 2 == 0) {
                        t = "bg-default";
                    } else {
                        t = "bg-info";
                    }
                    item += '<div class="row ' + t + '"> ';
                }
                p++;
                var e = data[x];
                item += li.replace("altnombre", e.name).replace("nombre", e.name).replace("url", e.url);
            }
            ;
            item += '</div>';
            $("#participantes").append(item);
        });


    </script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.6.0/Chart.js"></script>

    <script>
        var ctx = document.getElementById('genero').getContext('2d');
        var chart = new Chart(ctx, {
            // The type of chart we want to create
            type: 'pie',

            // The data for our dataset
            data: {
                labels: ["Masculino", "Femenino", "Otro",],
                datasets: [{
                    label: "Distribución por género",
                    backgroundColor: ['rgb(199, 30, 37)', 'rgb(112, 159, 44)', 'rgb(226, 189, 15)',],
                    borderColor: 'rgb(43, 57, 145)',
                    data: [{{genero.masculino}}, {{ genero.femenino }}, {{genero.otro}}],
                }]
            },

            // Configuration options go here
            options: {}
        });
    </script>


    <script>

        var ctx = document.getElementById('pais').getContext('2d');


        var myBarChart = new Chart(ctx, {
            type: 'horizontalBar',
            // The data for our dataset
            data: {
                labels: ['Panamá', 'Costa Rica', 'Nicaragua', 'El Salvador', 'Guatemala', 'Honduras', 'Belize', 'Otro'],
                datasets: [{
                    label: "Distribución por país",
                    backgroundColor: ['rgb(199, 30, 37)',
                        'rgb(112, 159, 44)',
                        'rgb(226, 189, 15)',
                        'rgb(199, 30, 37)',
                        'rgb(112, 159, 44)',
                        'rgb(226, 189, 15)',
                        'rgb(199, 30, 37)',
                        'rgb(112, 159, 44)'
                    ],
                    borderColor: 'rgb(43, 57, 145)',
                    data: [{{pais.panama}}, {{ pais.costarica }}, {{pais.nicaragua}},
                        {{pais.elsalvador}}, {{ pais.guatemala }}, {{pais.honduras}},
                        {{ pais.belize }}, {{pais.otro }}
                    ],
                }]
            },
            options: {}
        });

    </script>


{% endblock %}

src_ref/ecsl/templates/no_events.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block content %}
    <div class="container">
        <div class="container">
            <div class="row">
                <div class="col-md-8"><h1>Encuentro centroamericano de Software Libre </h1></div>
            </div>
        </div>
    </div>
    <br><br>
    <div class="row">
        <div class="col-md-12">
            <div class="well">
                <div class="row">
                    {% trans 'Sorry, but there are no events at the time.' %}
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

{% block js %}
    <script>
        var nav = document.getElementById("navbar");
        nav.style.display = "none";
    </script>
{% endblock js %}